upstream: https://github.com/community-scripts/ProxmoxVE
modsdir: codemods
codemods:
- description: Modify URLS
  mod: sed
  match: ct/*.sh
  args:
  - https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/misc/build.func
  - https://raw.githubusercontent.com/bketelsen/IncusScripts/main/misc/build.func
