upstream: https://github.com/community-scripts/ProxmoxVE
modsdir: codemods
stage: false
commit: false
push: true
ignorelist:
- prefix: frontend/
- prefix: turnkey/
- prefix: api/
- prefix: README
- prefix: LICENSE
- prefix: .github
- prefix: .gitignore
- prefix: .vscode
- prefix: json/add-lxc-iptag.json
- prefix: json/add-netbird-lxc.json
- prefix: json/add-tailscale-lxc.json
- prefix: json/all-templates.json
- prefix: json/clean-lxcs.json
- prefix: json/clean-orphaned-lvm.json
- prefix: json/cron-update-lxcs.json
- prefix: json/crowdsec.json
- prefix: json/fstrim.json
- prefix: json/host-backup.json
- prefix: json/kernel-clean.json
- prefix: json/kernel-pin.json
- prefix: json/lxc-delete.json
- prefix: json/microcode.json
- prefix: json/monitor-all.json
- prefix: json/netdata.json
- prefix: json/olivetin.json
- prefix: json/post-pbs-install.json
- prefix: json/post-pmg-install.json
- prefix: json/post-pve-install.json
- prefix: json/prometheus-pve-exporter.json
- prefix: json/scaling-governor.json
- prefix: json/turnkey.json
- prefix: json/update-lxcs.json
- prefix: json/update-repo.json
- prefix: json/pbs-microcode.json
- prefix: misc/pbs_microcode.sh
codemods:
- description: Whiptail install
  mod: sed
  match: install/*.sh
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail misc sh
  mod: sed
  match: misc/*.sh
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail misc func
  mod: sed
  match: misc/*.func
  args:
  - Proxmox VE Helper Scripts
  - Incus Scripts
- description: Whiptail func LXC
  mod: sed
  match: misc/*.func
  args:
  - LXC Container
  - Incus Container
- description: Default Bridge
  mod: sed
  match: misc/build.func
  args:
  - BRG="vmbr0"
  - BRG="incusbr0"
- description: Default hostname
  mod: sed
  match: misc/build.func
  args:
  - HN=$NSAPP
  - HN="${NSAPP}-${CT_ID}"

- description: Whiptail func Updater
  mod: sed
  match: misc/*.func
  args:
  - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/${app}.sh
  - https://github.com/bketelsen/IncusScripts/raw/main/ct/${app}.sh
- description: header location
  mod: sed
  match: misc/build.func
  args:
  - /usr/local/community-scripts/headers
  - $HOME/.config/incusscripts/headers
- description: uname arch
  mod: sed
  match: misc/build.func
  args:
  - "$(dpkg --print-architecture)"
  - "$(uname -m)"
- description: uname arch2
  mod: sed
  match: misc/build.func
  args:
  - "amd64"
  - "x86_64"
- description: Header Updates
  mod: sed
  match: misc/*.func
  args:
  - https://github.com/community-scripts/ProxmoxVE/raw/main/ct/headers/
  - https://github.com/bketelsen/IncusScripts/raw/main/ct/headers/
- description: PVE Check Function
  mod: bashfunc
  match: misc/build.func
  args:
  - pve_check
  - codemods/pve_check.sh
- description: PVE Description
  mod: bashfunc
  match: misc/build.func
  args:
  - description
  - codemods/description.sh
- description: Error Handler
  mod: bashfunc
  match: misc/install.func
  args:
  - error_handler
  - codemods/error_handler.sh
- description: Install wget
  mod: bashfunc
  match: misc/install.func
  args:
  - update_os
  - codemods/update_os.sh
- description: PVE Start Function
  mod: bashfunc
  match: misc/build.func
  args:
  - start
  - codemods/start.sh
- description: PVE Storage Function
  mod: bashfunc
  match: misc/build.func
  args:
  - check_container_storage
  - codemods/check_container_storage.sh
- description: PVE Build Function
  mod: bashfunc
  match: misc/build.func
  args:
  - build_container
  - codemods/build_container.sh
- description: Replace create_lxc
  mod: replacefile
  match: ct/create_lxc.sh
  args:
  - codemods/create_lxc.sh
- description: Replace install
  mod: bashfunc
  match: misc/build.func
  args:
  - install_script
  - codemods/install_script.sh
- description: FE config
  mod: sed
  match: frontend/next.config.mjs
  args:
  - ProxmoxVE
  - IncusScripts
- description: FE sitemap
  mod: sed
  match: frontend/src/app/sitemap.ts
  args:
  - community-scripts.github.io
  - bketelsen.github.io
- description: FE robots
  mod: sed
  match: frontend/src/app/robots.ts
  args:
  - community-scripts.github.io
  - bketelsen.github.io
- description: FE github
  mod: sed
  match: frontend/src/app/page.tsx
  args:
  - github.com/community-scripts
  - github.com/bketelsen
- description: FE title
  mod: sed
  match: frontend/src/app/page.tsx
  args:
  - Proxmox Helper
  - Incus Helper
- description: FE manifest
  mod: sed
  match: frontend/src/app/manifest.ts
  args:
  - Proxmox VE Helper-Scripts
  - Incus Helper Scripts
- description: FE manifest
  mod: sed
  match: frontend/src/app/layout.tsx
  args:
  - Proxmox VE Helper-Scripts
  - Incus Helper Scripts
- description: FE robots
  mod: sed
  match: frontend/src/app/layout.tsx
  args:
  - community-scripts.github.io
  - bketelsen.github.io
- description: FE ScriptInfoBlocks
  mod: sed
  match: frontend/src/app/scripts/_components/ScriptInfoBlocks.tsx
  args:
  - return "LXC";
  - return "CONTAINER";
- description: FE buttons
  mod: sed
  match: frontend/src/app/scripts/_components/ScriptItems/Buttons.tsx
  args:
  - https://raw.githubusercontent.com/community-scripts/
  - https://raw.githubusercontent.com/bketelsen/
- description: FE InstallCommand
  mod: sed
  match: frontend/src/app/scripts/_components/ScriptItems/InstallCommand.tsx
  args:
  - https://github.com/community-scripts/
  - https://github.com/bketelsen/
- description: FE category view
  mod: sed
  match: frontend/src/app/category-view/page.tsx
  args:
  - ProxmoxVE
  - IncusScripts
- description: FE Navbar
  mod: sed
  match: frontend/src/components/Navbar.tsx
  args:
  - Proxmox VE Helper-Scripts
  - Incus Helper-Scripts
- description: FE Navbar
  mod: sed
  match: frontend/src/components/Navbar.tsx
  args:
  - /ProxmoxVE/logo.png
  - /IncusScripts/logo.png
- description: FE Footer
  mod: sed
  match: frontend/src/components/Footer.tsx
  args:
  - https://github.com/community-scripts/
  - https://github.com/bketelsen/
- description: FE Command Menu
  mod: sed
  match: frontend/src/components/CommandMenu.tsx
  args:
  - LXC
  - CONTAINER
- description: FE Footer
  mod: sed
  match: frontend/src/config/siteConfig.tsx
  args:
  - https://github.com/community-scripts/
  - https://github.com/bketelsen/
- description: FE Star
  mod: sed
  match: frontend/src/components/ui/star-on-github-button.tsx
  args:
  - community-scripts
  - bketelsen
- description: JSON Execute
  mod: sed
  match: json/*.json
  args:
  - Execute within an existing LXC Console
  - Execute within an existing Incus Container
- description: FE Landing
  mod: sed
  match: frontend/src/app/page.tsx
  args:
  - Proxmox Virtual Environment (VE)
  - Incus
- description: FE Landing
  mod: sed
  match: frontend/src/app/page.tsx
  args:
  - Proxmox VE environment
  - Incus environment
- description: Inject Modification notice
  mod: inject
  match: install/*.sh
  args:
  - end
  - "# Modified by surgeon https://github.com/bketelsen/surgeon"
- description: Inject Modification notice
  mod: inject
  match: misc/*.func
  args:
  - start
  - "# Modified by surgeon https://github.com/bketelsen/surgeon"
