# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!
  BRANCHNAME: $(tr -dc A-Za-z0-9 </dev/urandom | head -c 13; echo)

includes:
  cli: ./cli 

tasks:
  update:
    cmds:
      - echo "Running surgeon..."
      - surgeon
      - ./misc/index.sh
    silent: true


  index:
    cmds:
      - echo "Creating index..."
      - ./misc/index.sh
    silent: true