# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  update:
    cmds:
      - echo "Running surgeon..."
      - surgeon
      - ./misc/index.sh
    silent: true
